CREATE TABLE [dbo].[Contact]
(
	[Id] INT NOT NULL IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
	[Phone] NVARCHAR(50) NOT NULL,
	[StreetAddress] NVARCHAR(100) NOT NULL,
	[Suburb] NVARCHAR(100) NOT NULL,
	[PostCode] NVARCHAR(20)  NOT NULL,
	CONSTRAINT PK_Contact PRIMARY KEY (Id)
)
